name: 'Validate SPFx Sample PR'
description: 'Verifies that an SPFx sample PR is valid'
inputs:
  pr: 
    required: true
    description: 'The PR to validate'
  validationRulesFile:
    required: true
    description: 'Path to the JSON file containing validation rules'
    default:  '.github/validate-sample-pr-rules.json'
runs:
  using: 'node20'
  main: 'dist/index.js'