name: Validate SPFx Web Parts Sample PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    if: github.event.pull_request.user.login != 'dependabot[bot]' && !contains(github.event.pull_request.labels.*.name, 'skip-validation')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Validate SPFx Sample PR Action
        uses: ./.github/actions/validate-sample-pr
        with:
          pr: ${{ toJson(github.event.pull_request) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
